language: scala
scala:
- 2.13.0
jobs:
  include:
  - stage: test
    script: sbt ++$TRAVIS_SCALA_VERSION test
  - stage: deploy
    if: branch = master AND tag =~ ^v 
    script: sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- rm -fv $HOME/.ivy2/.sbt.ivy.lock
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_5eaf5e1c6bb6_key
  -iv $encrypted_5eaf5e1c6bb6_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
env:
  global:
  - secure: EjuKO/RPLSdzXRu4hZApX62c+MTXJUav1oS2GsGCugi8bu26tNJ2UFot1ydr2Rj/HwxcNVpdYx8YYE9Pnu/ng2l2AQy7Zbhzj4IoUUchQWdyUdshOvv1MiNMkSSaOd9cXSe+dG+OMHzN8GHtlhRLHgVTivbP+DofzJwT60noS07YHQ5vGfdnnGKzFIxkK9NyBgl0PwUqWWVbglRnpHAODZY6DDK/H9eNsbOchonLcDHArxbVFHAx6eTnUXZo/exKHH5x8A/DgJ0hFVqLVprXwuaK3V5ZDqWSJpwzkyQ+Vzi+1A9cSBYsqWSiKJ3oBw7V0leEzGiMyUURYbPhJEziWqo9kZF30dnHAy33JHt8CRke/B5j8fd30hr1xkjTAUAiQgWa2gz+RK7gFvQqPIh1YRlXFxvbz3WOXq1ioq0DlExVexZ2JgS2baHKSteS2VKypmP08EA19hzN/QOsezdeHTSt04UqDTtHJK6kh9bSCPtCPMy9MJt9MuPXU22ufzqbb9S2l9Zoxup3JqoasDLsb6mrupNO0xl5D9ByDLOK9XQM3Renvv1zf8Rn/xcUDguXtwGxMjJvWiTDK7xqMN1JX5GM4Hc6SNH4GqrJJR52/FPUcl2lDBFPKkRnHIy3oRZ9LeSBd10Ggy2xe+YeeMM1dAxI3eu+7uvx06Enl/hazF8=
  - secure: tEcRPdW+zKMkm+fEfDvHz2Bwsw2/VAV31D4SoQXpcyBPSIddwr1HwvRWrAlveLrvUaWMB25VfkdUaEq4D6Bo5PkOo24TvfzhTTZAEPYfDSmYJ0LFgDXwCoTtBKom2blWnfRMgHEHitzsRnEu/TM1b9gKyHIepsYPgRjLEDAvb1HXt2nb1r9P3LxRUde0Zd/13s0mE5YjplTMYO2+esZNVfFY924f+ds+o8x4+RP2Nf6GEE9ShURfVg/Wxf+PaWHfTEseA4d3HWuHhviindy5Tfros+MtcsFZ9gUTUPntCMWpaXOn5+JZrJ7Ozou79sNfKYe1FmlhJvd8X/l2c32txo+3IXCHjc9gLNvOle+re5TQ4l+S99VgQd4/s/ku2MV8/+fPSV3/sPwSmaDI+edFyslhtaHqcgpGo3X43VZXEevPtu/xVfKMFm/Hi2kNHLaIWL5AhoSlUdmy3uI809Vsy2lJ7mnLkh/FIBDAyML+ombMo0UzmNA+L4PmLCMnuyjqKwI6qxwow5JWYuYKPzfObey/oxPly8B7545MDvcMlHQKAh+71HGFW/DTjVMKhrGXJQNfwMFTrWLD9ymz2sxSkHp5JEnOlbyHtmYtwwoQ1Z6clZBT+uZO3YP/b+Nbbtq7wC+iRFlVNa/CIqr29NVowLFboGSMTvYyjoEDDIOC76g=
  - secure: oa4IgrRMNsqO2n1D7r63pewBGPl3XZxZWoZVltwLghEV/BsY4tMyiXDSAhjlM3+uoOCutmYQGWq1QKP7DIZv6U2EDTUakaSKn4zKedS64ZolnAm2yz0kQYoHLUDuYZMyrkKaDo57xBXjPXjQtBO7YI0HdbTOZrUpCULbJIBjPdpVwwk/HRQA9ab6TLsO5M/+Ypleqiu9JGCBQfAKgIzTTK8NQpuIOGsS+qgaugZBiQ5pzo0WSiyn606rbx9FUStT4C39vN3noMmHpPsxsY36R6pbYJa2yw+CoNyMhDq4RnD8rEnNlOXHdYWvlhdwpupEqC+f8dKGC8QZymy7TuYpItXqMlj42JyaPcy6LYJ5DT94Wi8VeIFPC0vphf/Xv+++i1o8Eyn3z+XTwUzufbuD+ZF9TI08Btk6mw96IMv2s5U69ZMotc8lsAsDqnhm6a+k9zdXYUHjsJuLhYLun2k9SQDg+dLrGPd/TImt8shOpct6UEtMTcYB/9ghkRasRP3XOjf1GuA2zrf6D2hTxT/2YTFL2TDmaQmAKaVCxlHLr2ZOtNsiVnxg11ETYbDKMTyNBLP4D5GYk6Gqv/3Zu1YZRc2tU4toIqbMUHOhEwVHkGh6GRfXhuL9Ja+wcMmGBInBP3Ita2XcHH3yzsnOUWPmSgwYYf+Aqy+LcYIq0AC7EIw=
